In [14]:
ORIGIN_PATH = "./.."

In [15]:
PATH_GRAPHEIN = "Graphein_notebooks"
PATH_PDB = "PDBGraphStore_notebooks"

In [16]:
T = "time"
MEM = "memory"

In [17]:
b = "baseline"
gnn = "gnn"
tdc = "tdc"

In [18]:
datasets = [b, gnn, tdc]

In [19]:
aproaches = [PATH_GRAPHEIN, PATH_PDB]

## Workflow

In [20]:
import numpy as np
import pandas as pd

In [50]:
mem_df = pd.DataFrame(
    index=["baseline", "tdc", "gnn"],
    columns=["graphein", "pdb"],
    dtype=float,
)

# mapeia o nome da pasta para o nome da coluna
col_map = {
    "Graphein_notebooks": "graphein",
    "PDBGraphStore_notebooks": "pdb",
}

for ap in aproaches:
    for ds in datasets:
        print(f"{ap}/{ds}")

        with open(f"{ORIGIN_PATH}/{ap}/{ds}_{T}.txt", "r") as f:
            s = f.read()
            l = s.split("\n")
            l = [float(i) for i in l]

            avg = np.average(l)
            print(f'time avg (s): {avg}')
            print(f'timestdev: {np.std(l)}')

        mem_l = []

        with open(f"{ORIGIN_PATH}/{ap}/{ds}_{MEM}.txt", "r") as f:
            mem_l = [i.split("/")[0].strip() for i in f.read().split("\n") if i.strip()]

        for i in range(len(mem_l)):
            if "M" in mem_l[i]:
                mem_l[i] = float(mem_l[i].split("M")[0])
            elif "G" in mem_l[i]:
                mem_l[i] = float(mem_l[i].split("G")[0]) * 1000

        mem_df.loc[ds, col_map[ap]] = np.max(mem_l)
        print("\n")

mem_df.head()

Graphein_notebooks/baseline
time avg (s): 409.62347888946533
timestdev: 29.358292830904812
memory: 2293.0


Graphein_notebooks/gnn
time avg (s): 1697.5383400917053
timestdev: 93.5071687179896
memory: 7299.0


Graphein_notebooks/tdc
time avg (s): 1130.7317974090577
timestdev: 70.6154166686822
memory: 7199.0


PDBGraphStore_notebooks/baseline
time avg (s): 452.8189173221588
timestdev: 24.61764638714008
memory: 2139.0


PDBGraphStore_notebooks/gnn
time avg (s): 2233.589607429504
timestdev: 114.10774731291174
memory: 5532.0


PDBGraphStore_notebooks/tdc
time avg (s): 1424.5653676509858
timestdev: 92.48654048837118
memory: 4608.0

          graphein     pdb
baseline    2293.0  2139.0
tdc         7199.0  4608.0
gnn         7299.0  5532.0

In [25]:
mem_df["compression_ratio"] = 1 - mem_df['pdb']/mem_df['graphein']
mem_df.head()

          graphein     pdb  compression_ratio
baseline    2293.0  2139.0           0.067161
tdc         7199.0  4608.0           0.359911
gnn         7299.0  5532.0           0.242088

## Structure

In [1]:
import pandas as pd

In [11]:
df = pd.read_csv('structure_memory.csv')
df.head()

   workflow     graphein          pdb
0  baseline   766.704247   500.441246
1       gnn  4735.778397  2370.377640
2       tdc  4804.447411  2370.943100

In [9]:
df["compression_ratio"] = 1 - df["pdb"] / df['graphein']

In [10]:
df.head()

   workflow     graphein          pdb  compression_ratio
0  baseline   766.704247   500.441246           0.347283
1       gnn  4735.778397  2370.377640           0.499475
2       tdc  4804.447411  2370.943100           0.506511